// crud-react/src/components/editar.js
import React from 'react';
import { Link } from 'react-router-dom';


class Editar extends React.Component {

	constructor(props) {
		super(props);
		this.state = {
			nombre:"",
			correo:""
		}
	}

	componentDidMount() 
	{
		let id = this.props.match.params.id;

		fetch("http://localhost:80/crud/cons-uno.php?id="+id)
		.then(resp => resp.json())
		.then(resp => {
			this.setState({
				nombre: resp['nombre'],
				correo: resp['correo']
			})
		})
	}


	cambioValor = (e) => 
	{ 
		const state = this.state;
		state[e.target.name] = e.target.value;
		this.setState({ state })
	}

	editar = (e) =>
	{
		e.preventDefault();	

		const{nombre, correo} = this.state;

		var datos = { id:this.props.match.params.id, nombre:nombre, correo:correo}

		fetch("http://localhost:80/crud/editar.php", {
			method: "POST",
			body: JSON.stringify(datos)
		})
		.then(resp => resp.json())
		.then(resp => {
			this.props.history.push("/")
		})
		.catch(console.log)
	}


	render() 
	{
		const{nombre, correo} = this.state;

		return (
			<div>
				<div className="card-header">
					<h2>Editar</h2>
				</div>


				<div className="card-body">

					<Link className="btn btn-secondary btn-sm" to={"/"}>Volver</Link>

					<form className="mt-3" onSubmit={this.editar}>

						<div className="form-group">
							<label className="form-label">Nombre</label>
							<input type="text" name="nombre" id="nombre" className="form-control" onChange={this.cambioValor} value={nombre} />
						</div>

						<div className="form-group">
							<label className="form-label">Correo</label>
							<input type="email" name="correo" id="correo" className="form-control" onChange={this.cambioValor} value={correo} />
						</div>


						<button type="submit" className="btn btn-primary">Editar</button>

					</form>

				</div>
			</div>

		)
	}
		

}

export default Editar

// crud-vue/src/components/Editar.vue
<template>
	
	<div class="card-header">
		<h2>Editar</h2>
	</div>

	<!-- Card -->
	<div class="card-body">

		<router-link to="/" class="btn btn-secondary btn-sm">Volver</router-link>

		<form class="mt-3" v-on:submit.prevent="editar">
			
			<div class="form-group">
				<label class="form-label">Nombre</label>
				<input type="text" name="nombre" id="nombre" class="form-control" v-model="user.nombre">
			</div>

			<div class="form-group">
				<label class="form-label">Correo</label>
				<input type="email" name="correo" id="correo" class="form-control" v-model="user.correo">
			</div>

			
			<button type="submit" class="btn btn-primary">Editar</button>


		</form>

	</div>
</template>


<script>
	
	export default {

		data() {

			return {
				user: {}
			}

		},

		created: function() {

			this.consUno();

		},

		methods: {

			consUno() 
			{
				fetch('http://localhost:80/crud/cons-uno.php?id='+this.$route.params.id)
				.then(resp => resp.json())
				.then(resp =>  this.user = resp )
			},

			editar() 
			{
				var datosEnviar = {  id: this.$route.params.id, 
											nombre: this.user.nombre, 
											correo: this.user.correo }

				fetch('http://localhost:80/crud/editar.php', {
					method: 'POST',
					body: JSON.stringify(datosEnviar)
				})
				.then(resp => resp.json())
				.then(resp => {
					console.log(resp)
					location.href = '/#/'
				})

			}

		}

	}

</script>
